import React, { useState } from 'react';
import { analyzeEvidence } from '../services/api';

function HershieldImporter({ showSwahili, hersheidEvidence, onEvidenceImport, onAnalyzeEvidence }) {
  const [isAnalyzing, setIsAnalyzing] = useState(false);
  const [blurredContent, setBlurredContent] = useState(true);

  // Enhanced test import with different formats
  const handleTestImport = () => {
    if (onEvidenceImport) {
      const testEvidence = {
        evidence: {
          commentCount: 3,
          platforms: ['twitter'],
          importedFrom: 'manual_test',
          content: 'you ugly', // Test with insult
          comments: [
            { text: 'you are so ugly', platform: 'twitter' },
            { text: 'stupid person', platform: 'twitter' }
          ]
        }
      };
      onEvidenceImport(testEvidence);
      alert(showSwahili ? '✅ Ushahidi umeingizwa kikamilifu!' : '✅ Evidence imported successfully!');
    }
  };

  // Download evidence as PDF
  const handleDownloadPDF = () => {
    if (!hersheidEvidence.length) {
      alert(showSwahili ? 'Hakuna ushahidi wa kupakua' : 'No evidence to download');
      return;
    }

    try {
      // Create PDF content
      const pdfContent = {
        title: 'ShieldHer Evidence Report',
        date: new Date().toLocaleDateString(),
        evidence: hersheidEvidence.map((evidence, index) => ({
          id: index + 1,
          platform: evidence.evidence?.platforms?.[0] || 'unknown',
          commentCount: evidence.evidence?.commentCount || 1,
          content: evidence.evidence?.content || 'No content',
          timestamp: evidence.importedAt || new Date().toISOString()
        }))
      };

      // Create PDF using browser print functionality
      const printWindow = window.open('', '_blank');
      printWindow.document.write(`
        <!DOCTYPE html>
        <html>
        <head>
          <title>ShieldHer Evidence Report</title>
          <style>
            body { 
              font-family: Arial, sans-serif; 
              margin: 40px; 
              line-height: 1.6;
            }
            .header { 
              text-align: center; 
              border-bottom: 2px solid #333; 
              padding-bottom: 20px; 
              margin-bottom: 30px;
            }
            .evidence-item { 
              margin-bottom: 25px; 
              padding: 15px; 
              border: 1px solid #ddd; 
              border-radius: 8px;
            }
            .evidence-content {
              background: #f5f5f5;
              padding: 10px;
              border-radius: 4px;
              margin: 10px 0;
              font-style: italic;
            }
            .footer {
              margin-top: 40px;
              text-align: center;
              font-size: 12px;
              color: #666;
            }
            @media print {
              body { margin: 0; }
            }
          </style>
        </head>
        <body>
          <div class="header">
            <h1>🛡️ ShieldHer Evidence Report</h1>
            <p>Generated on: ${new Date().toLocaleDateString()}</p>
            <p>Total Evidence Items: ${hersheidEvidence.length}</p>
          </div>

          ${pdfContent.evidence.map(item => `
            <div class="evidence-item">
              <h3>Evidence #${item.id}</h3>
              <p><strong>Platform:</strong> ${item.platform}</p>
              <p><strong>Comments:</strong> ${item.commentCount}</p>
              <p><strong>Content Preview:</strong></p>
              <div class="evidence-content">
                ${item.content.substring(0, 200)}${item.content.length > 200 ? '...' : ''}
              </div>
              <p><strong>Date:</strong> ${new Date(item.timestamp).toLocaleString()}</p>
            </div>
          `).join('')}

          <div class="footer">
            <p>This report was generated by ShieldHer - Online Harassment Protection Tool</p>
            <p>Confidential - For personal use only</p>
          </div>
        </body>
        </html>
      `);
      
      printWindow.document.close();
      
      // Wait for content to load then print/download
      setTimeout(() => {
        printWindow.print();
      }, 500);

    } catch (error) {
      console.error('PDF generation failed:', error);
      alert(showSwahili ? 'Hitilafu katika kutengeneza PDF' : 'Error generating PDF');
    }
  };

  // === ADD THIS NEW FUNCTION ===
  const handleClearAllData = () => {
    if (!confirm(showSwahili 
      ? 'Una uhakika unataka kufuta data YOTE? Hii itafuta ushahidi, kuchambua, na mipangilio.' 
      : 'Are you sure you want to delete ALL data? This will clear evidence, analysis, and settings.'
    )) {
      return;
    }

    try {
      // Clear all app data
      localStorage.clear();
      sessionStorage.clear();
      
      // Clear cookies for your app
      const domain = window.location.hostname;
      document.cookie.split(';').forEach(cookie => {
        const eqPos = cookie.indexOf('=');
        const name = eqPos > -1 ? cookie.substr(0, eqPos).trim() : cookie.trim();
        document.cookie = `${name}=;expires=Thu, 01 Jan 1970 00:00:00 GMT;path=/;domain=${domain}`;
      });
      
      alert(showSwahili 
        ? '✅ Data yote imefutwa! Programu itaanzwa upya.' 
        : '✅ All data cleared! App will restart.'
      );
      
      // Reload the application
      setTimeout(() => {
        window.location.reload();
      }, 1000);
      
    } catch (error) {
      console.error('Error clearing data:', error);
      alert(showSwahili 
        ? '❌ Hitilafu katika kufuta data' 
        : '❌ Error clearing data'
      );
    }
  };

  // Enhanced analysis that handles different evidence formats
  const handleAnalyzeEvidence = async () => {
    if (!hersheidEvidence.length) {
      alert(showSwahili ? 'Hakuna ushahidi wa kuchambua' : 'No evidence to analyze');
      return;
    }

    setIsAnalyzing(true);
    try {
      console.log('🔍 ALL EVIDENCE TO ANALYZE:', hersheidEvidence);
      
      // Extract message content from different evidence formats
      const evidenceData = hersheidEvidence.map(evidence => {
        const content = 
          evidence.evidence?.content || 
          evidence.content ||
          (evidence.evidence?.comments?.[0]?.text) ||
          evidence.text ||
          '';
        
        const platform = 
          evidence.evidence?.platforms?.[0] ||
          evidence.evidence?.platform ||
          evidence.platform ||
          'unknown';

        return {
          source: platform,
          count: evidence.evidence?.commentCount || 1,
          timestamp: evidence.importedAt ? new Date(evidence.importedAt).toLocaleTimeString() : 'Just now',
          content: content
        };
      });

      console.log('📊 PROCESSED EVIDENCE DATA:', evidenceData);

      // Check if we have any content to analyze
      const hasContent = evidenceData.some(item => item.content && item.content.trim());
      
      if (!hasContent) {
        const fallbackAnalysis = {
          severity: 'Medium',
          summary: `Found ${hersheidEvidence.length} imported comments (no message content)`,
          autoSelected: ['Document Evidence', 'Calm Response Template 1']
        };
        
        if (onAnalyzeEvidence) {
          onAnalyzeEvidence(fallbackAnalysis, hersheidEvidence);
        }
        return;
      }

      const analysisResult = await analyzeEvidence(evidenceData);
      
      console.log('🎯 ANALYSIS RESULT:', analysisResult);
      
      if (onAnalyzeEvidence) {
        onAnalyzeEvidence(analysisResult, hersheidEvidence);
      }
      
    } catch (error) {
      console.error('Analysis failed:', error);
      alert(showSwahili ? 'Hitilafu katika kuchambua' : 'Analysis failed');
      
      const fallbackAnalysis = {
        severity: 'Medium',
        summary: `Found ${hersheidEvidence.length} imported comments`,
        autoSelected: ['Document Evidence', 'Calm Response Template 1']
      };
      
      if (onAnalyzeEvidence) {
        onAnalyzeEvidence(fallbackAnalysis, hersheidEvidence);
      }
    } finally {
      setIsAnalyzing(false);
    }
  };

  // Enhanced evidence display with blur functionality
  const renderEvidenceContent = (evidence) => {
    const content = 
      evidence.evidence?.content || 
      evidence.content ||
      (evidence.evidence?.comments?.[0]?.text) ||
      evidence.text;

    if (content) {
      return (
        <div className="mt-2">
          <p className={`text-sm text-gray-700 italic transition-all duration-300 ${
            blurredContent ? 'filter blur-sm' : 'filter blur-0'
          }`}>
            "{content}"
          </p>
          <button
            onClick={() => setBlurredContent(!blurredContent)}
            className="text-xs text-blue-600 hover:text-blue-800 mt-1"
          >
            {blurredContent ? 
              (showSwahili ? 'Onyesha Maudhi' : 'Show Content') : 
              (showSwahili ? 'Ficha Maudhi' : 'Hide Content')
            }
          </button>
        </div>
      );
    }
    
    return (
      <p className="text-xs text-gray-500 mt-1">
        No message content found
      </p>
    );
  };

  return (
    <div className="text-center space-y-6">
      {/* Header */}
      <div className="bg-white rounded-xl p-8 border-2 border-dashed border-purple-300">
        <div className="text-4xl mb-4">🛡️</div>
        <h2 className="text-2xl font-bold text-gray-800 mb-2">
          {showSwahili ? 'Hershield Importer' : 'Hershield Importer'}
        </h2>
        <p className="text-gray-600 mb-4">
          {showSwahili 
            ? 'Tumia kiendelezi cha Hershield kutuma ushahidi moja kwa moja'
            : 'Use the Hershield extension to send evidence directly'
          }
        </p>
        
        {/* Test Import Button */}
        <button
          onClick={handleTestImport}
          className="mb-4 px-4 py-2 bg-blue-500 text-white rounded-lg hover:bg-blue-600 text-sm"
        >
          {showSwahili ? 'Jaribu Kuingiza (maudhi)' : 'Test Import (insults)'}
        </button>
        
        <div className="bg-purple-50 rounded-lg p-4 text-left">
          <h3 className="font-semibold text-purple-800 mb-2">
            {showSwahili ? 'Hatua za Kufuata:' : 'How to use:'}
          </h3>
          <ol className="text-sm text-purple-700 space-y-1">
            <li>1. {showSwahili ? 'Tembelea Twitter/Facebook' : 'Visit Twitter/Facebook'}</li>
            <li>2. {showSwahili ? 'Bonyeza kiendelezi cha Hershield' : 'Click the Hershield extension'}</li>
            <li>3. {showSwahili ? 'Chagua maoni ya unyanyasaji' : 'Select harassment comments'}</li>
            <li>4. {showSwahili ? 'Bonyeza "Tuma kwa App"' : 'Click "Send to App"'}</li>
            <li>5. {showSwahili ? 'Ushahidi utaonekana hapa!' : 'Evidence will appear here!'}</li>
          </ol>
        </div>
      </div>

      {/* Evidence Display */}
      {hersheidEvidence.length > 0 && (
        <div className="bg-white rounded-xl p-6">
          <div className="flex justify-between items-center mb-4">
            <h3 className="text-lg font-semibold text-gray-800">
              {showSwahili ? 'Ushahidi Ulioingizwa' : 'Imported Evidence'} 
              <span className="ml-2 bg-green-100 text-green-800 px-2 py-1 rounded-full text-sm">
                {hersheidEvidence.length}
              </span>
            </h3>
            
            {/* Download PDF Button */}
            <button
              onClick={handleDownloadPDF}
              className="flex items-center gap-2 px-4 py-2 bg-red-600 text-white rounded-lg hover:bg-red-700 text-sm"
            >
              📄 {showSwahili ? 'Pakua PDF' : 'Download PDF'}
            </button>
          </div>
          
          <div className="space-y-3">
            {hersheidEvidence.map((evidence, index) => (
              <div key={evidence.id || index} className="flex items-center justify-between p-3 bg-gray-50 rounded-lg">
                <div className="flex-1">
                  <div className="flex items-center gap-2">
                    <span className="font-medium">
                      {evidence.evidence?.commentCount || 1} {showSwahili ? 'maoni' : 'comments'}
                    </span>
                    <span className="text-sm text-gray-600">
                      {evidence.evidence?.platforms?.join(', ') || evidence.evidence?.platform || evidence.platform || 'unknown'}
                    </span>
                  </div>
                  {renderEvidenceContent(evidence)}
                </div>
                <span className="text-xs text-gray-500">
                  {evidence.importedAt ? new Date(evidence.importedAt).toLocaleTimeString() : 'Just now'}
                </span>
              </div>
            ))}
          </div>

          {/* Action Buttons */}
          <div className="mt-6 pt-4 border-t border-gray-200 space-y-3">
            {/* Toggle Blur Button */}
            <button
              onClick={() => setBlurredContent(!blurredContent)}
              className="w-full py-2 bg-gray-600 text-white rounded-lg hover:bg-gray-700"
            >
              {blurredContent ? 
                (showSwahili ? '🔓 Oonesha Yaliyomo' : '🔓 Show Content') : 
                (showSwahili ? '🔒 Ficha Yaliyomo' : '🔒 Hide Content')
              }
            </button>

            {/* Analyze Evidence Button */}
            <button
              onClick={handleAnalyzeEvidence}
              disabled={isAnalyzing}
              className={`w-full py-3 rounded-lg font-semibold flex items-center justify-center gap-2 transition-colors ${
                isAnalyzing 
                  ? 'bg-gray-400 cursor-not-allowed' 
                  : 'bg-green-600 hover:bg-green-700 text-white'
              }`}
            >
              {isAnalyzing ? (
                <>
                  <div className="animate-spin rounded-full h-5 w-5 border-b-2 border-white"></div>
                  {showSwahili ? 'Inachambua...' : 'Analyzing...'}
                </>
              ) : (
                <>
                  🔍 {showSwahili ? 'Chambua Ushahidi' : 'Analyze Evidence'}
                </>
              )}
            </button>

            {/* === ADD THIS NEW CLEAR DATA BUTTON === */}
            <button
              onClick={handleClearAllData}
              className="w-full py-2 bg-red-600 text-white rounded-lg hover:bg-red-700 flex items-center justify-center gap-2"
            >
              🗑️ {showSwahili ? 'Futa Data Yote' : 'Clear All Data'}
            </button>
            
            <p className="text-sm text-gray-600">
              {showSwahili 
                ? 'Chambua ushahidi na upate majibu salama ya kisheria'
                : 'Analyze evidence and get safe, legal responses'
              }
            </p>
          </div>
        </div>
      )}

      {/* Waiting State */}
      {hersheidEvidence.length === 0 && (
        <div className="bg-yellow-50 border border-yellow-200 rounded-xl p-6">
          <div className="text-2xl mb-2">⏳</div>
          <p className="text-yellow-800">
            {showSwahili 
              ? 'Inasubiri ushahidi kutoka kwa kiendelezi...'
              : 'Waiting for evidence from extension...'
            }
          </p>
          <p className="text-yellow-700 text-sm mt-2">
            {showSwahili 
              ? 'Tumia kiendelezi cha Hershield kwenye Twitter au Facebook'
              : 'Use the Hershield extension on Twitter or Facebook'
            }
          </p>
        </div>
      )}
    </div>
  );
}

export default HershieldImporter;